# Generated by Django 3.0.6 on 2020-06-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.TextField()),
                ('page_url', models.TextField()),
                ('mpaa', models.TextField()),
                ('genre', models.TextField()),
                ('year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('director', models.TextField()),
            ],
        ),
    ]
